### ISSUE TITLE
Code request

### ISSUE THREAD

**Issue by GFZShiwai** [X-PLUG/mPLUG-2#1]
Hi, will you open source the pre-training code for the model and around when will it be available?

**Comment by yahooo-m** [comment]
Mark!

**Comment by chengengliu** [comment]
+1

**Comment by MAGAer13** [comment]
We will release the code and the pre-trained weight this week.

**Comment by mmaaz60** [comment]
@GFZShiwai I request you to provide a colab or a simple inference script as well, thanks
