### ISSUE TITLE
When are you gonna share the weights?

### ISSUE THREAD

**Issue by aartykov** [X-PLUG/mPLUG-2#2]
Hello! Thank you for the excellent work. My question is when are you gonna share the weight checkpoints? 
Thanks in advance!

**Comment by aartykov** [comment]
The provided links for weights do not work.

**Comment by MAGAer13** [comment]
Which weight?

**Comment by aartykov** [comment]
@MAGAer13 I can't download any of the video caption and video QA checkpoints. When I click on the link, it does not respond.

**Comment by MAGAer13** [comment]
Try to use 'wget' to download via command line?
