### ISSUE TITLE
Could you provide the JSON file in the video captioning task?

### ISSUE THREAD

**Issue by myccver** [X-PLUG/mPLUG-2#3]
Thank you for your excellent work! However, I noticed that there are missing JSON files in the MSRVTT and MSVD datasets that your code requires.  Could you provide them?"

**Comment by ChdDongyang** [comment]
> 
May I ask if you have obtained these files and where did you get them?

**Comment by myccver** [comment]
> > 
> 
> May I ask if you have obtained these files and where did you get them?

Please refer to the following format:
'''
Video Captioning Dataset

jsonl format [
    {"video_id": str, "caption": str}, or {"video_id": str, "golden_caption": List[str]}
    xxxx
]
'''

**Comment by ChdDongyang** [comment]
> > > 
> > 
> > 
> > May I ask if you have obtained these files and where did you get them?
> 
> Please refer to the following format: ''' Video Captioning Dataset
> 
> jsonl format [ {"video_id": str, "caption": str}, or {"video_id": str, "golden_caption": List[str]} xxxx ] '''

OK, thank you very much!

**Comment by rose-jinyang** [comment]
Hello @Roleone123 and @MAGAer13 
Could you provide the URLs to MSVD and MSR_VTT datasets for video captioning?

**Comment by idj3tboy** [comment]
I request if the author can provide us with the jsonl files of the train and test partitions.
Thank you.
