### ISSUE TITLE
How to perform CIDEr optimization?

### ISSUE THREAD

**Issue by KaiGod0730** [X-PLUG/mPLUG-2#4]
Thank you for your excellent work! The paper mentions that CIDEr optimization has been performed for extra 5 epochs in video captioning task. How to run CIDEr optimization using your code?

**Comment by MAGAer13** [comment]
Please refer to the repo of mPLUG.
https://github.com/X-PLUG/mPLUG/blob/main/caption_mplug_scst.py

**Comment by KaiGod0730** [comment]
In the repo of mPLUG-2, model_video_caption.py, Line 105, I found 'MPLUG2' object has no attribute '_flatten_time'. How to use '_flatten_time'? @MAGAer13

**Comment by MAGAer13** [comment]
Hi, it's a legacy in the model. We do not use self.beam_search in the model.
