### ISSUE TITLE
Code for Video Text Retrieval

### ISSUE THREAD

**Issue by Hritikbansal** [X-PLUG/mPLUG-2#5]
Hi, great work!

Can you provide a script to run Video-Text Retrieval with m-PLug2?

**Comment by MAGAer13** [comment]
You can refer the code in mPLUG for video-text retrieval. Basically they are similar.

**Comment by Hritikbansal** [comment]
![image](https://github.com/X-PLUG/mPLUG-2/assets/28641936/3f296c4c-e069-420f-aeb4-d2cf3c5aedfe)
Hi, 

Which embeddings in this figure did you use as language and vision representations for zero-shot video-text retrieval?
